# Generated by Django 6.0.3 on 2026-03-28 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('client_id', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('similarity_threshold', models.DecimalField(decimal_places=2, default=0.75, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('embedding_model', models.CharField(default='simple-keyword', max_length=120)),
                ('chunk_size', models.PositiveIntegerField(default=1000)),
                ('chunk_overlap', models.PositiveIntegerField(default=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('ollama', 'Ollama'), ('custom', '自定义')], max_length=20)),
                ('model_name', models.CharField(max_length=120)),
                ('api_base', models.URLField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('context_window', models.PositiveIntegerField(default=16000)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.3, max_digits=3)),
                ('max_tokens', models.PositiveIntegerField(default=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(default='info', max_length=20)),
                ('action', models.CharField(max_length=120)),
                ('detail', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('parameters', models.JSONField(blank=True, default=list)),
                ('is_builtin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SensitiveWordSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手'), ('system', '系统')], max_length=20)),
                ('content', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('alternate_questions', models.JSONField(blank=True, default=list)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('faq_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.faqset')),
            ],
            options={
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('object_name', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processed', '已处理'), ('failed', '失败')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.knowledgebase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('system_prompt', models.TextField(default='你是企业知识库助手，请仅根据提供的知识库上下文作答；如果没有相关信息，请明确说明。')),
                ('enable_rerank', models.BooleanField(default=False)),
                ('top_k', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('faq_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenes', to='core.faqset')),
                ('knowledge_bases', models.ManyToManyField(blank=True, related_name='scenes', to='core.knowledgebase')),
                ('model_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenes', to='core.modelprovider')),
                ('plugins', models.ManyToManyField(blank=True, related_name='scenes', to='core.plugin')),
                ('sensitive_word_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenes', to='core.sensitivewordset')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.scene'),
        ),
        migrations.CreateModel(
            name='SensitiveWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(max_length=120)),
                ('replace_with', models.CharField(blank=True, max_length=120)),
                ('reject_directly', models.BooleanField(default=False)),
                ('word_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='core.sensitivewordset')),
            ],
            options={
                'ordering': ['word'],
                'unique_together': {('word_set', 'word')},
            },
        ),
    ]
